###prompts
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

from model import model

Supervisor_prompt=PromptTemplate(
    template="""
            You are supervisor bot for a task to generate report of particular student to user. The steps of the task include calling Analysis Agent which analysis given output of student data,
            then supervisor call Summary agent which provide summary of analysis output to user, then supervisor call Graph agent to print graph of student data to user.
            You rae mainly responsible for managing the conversation between the member Agent. {members}.
            Look at the last call node {last_call_node} and determine which member agent is called to be next.
            Given the following user request: {user_query}, respond with the worker to act next. Each worker will perform a task and respond with their result and status. When finish respond with "FINISH".
            When you provide answer, please reply in one of the following memeber names according to the task.
            1. Analysis
            2. Summary

            User Request : \n\n {user_query} \n\n
            Members : {members}
            last_call_node: {last_call_node}

    """,
    input_variables=[
        "user_query",
        "members",
        "last_call_node",
    ],
)

Supervisor_prompt_chain=Supervisor_prompt|model|StrOutputParser()

Analysis_prompt=PromptTemplate(
    template="""
            You are Analysis Agent . Your role is to analysis student data {student_data}. use this dictionary as context {student_data} and analyse all data and give your response to 
            Summary Agent. when finished respond with Thanks .

            student_data: \n\n {student_data} \n\n

        """,
# input_variables=["student_data"],
)
Analysis_prompt_chain=Analysis_prompt|model|StrOutputParser()


Summary_prompt=PromptTemplate(
    template=""" 
            You are summary generator agent. you are responsible for creating summary of the  analysis agent output. You will be provided by analysis_output {analysis_output} that 
            are generated by analysis agent.

            Analysis_output: \n\n {analysis_output} \n\n 
    """,
)
Summary_prompt_chain=Summary_prompt|model| StrOutputParser()


